name: service-bus-poc-emulator
services:
  emulator:
    container_name: "servicebus-emulator"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    pull_policy: always
    volumes:
      - "./config.json:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
      - "5300:${EMULATOR_HTTP_PORT:-5300}"
    environment:
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: "${SQL_PASSWORD}"
      ACCEPT_EULA: ${ACCEPT_EULA:-Y}
      SQL_WAIT_INTERVAL: ${SQL_WAIT_INTERVAL:-15}
      EMULATOR_HTTP_PORT: ${EMULATOR_HTTP_PORT:-5300}
    depends_on:
      - sqledge
    networks:
      sb-emulator:
        aliases:
          - "sb-emulator"
  sqledge:
    container_name: "sqledge"
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    networks:
      sb-emulator:
        aliases:
          - "sqledge"
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA:-Y}
      MSSQL_SA_PASSWORD: "${SQL_PASSWORD}"

networks:
  sb-emulator:
