<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Moq" Version="4.20.70" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/ServiceBusPoc.Core/ServiceBusPoc.Core.csproj" />
    <ProjectReference Include="../../src/ServiceBusPoc.Carwash/ServiceBusPoc.Carwash.csproj" />
    <ProjectReference Include="../../src/ServiceBusPoc.Dashboard/ServiceBusPoc.Dashboard.csproj" />
    <ProjectReference Include="../../src/ServiceBusPoc.DigitalChannels/ServiceBusPoc.DigitalChannels.csproj" />
    <ProjectReference Include="../../src/ServiceBusPoc.Insurance/ServiceBusPoc.Insurance.csproj" />
    <ProjectReference Include="../../src/ServiceBusPoc.ParksResorts/ServiceBusPoc.ParksResorts.csproj" />
    <ProjectReference Include="../../src/ServiceBusPoc.Producer/ServiceBusPoc.Producer.csproj" />
    <ProjectReference Include="../../src/ServiceBusPoc.Verifier/ServiceBusPoc.Verifier.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Moq" />
    <Using Include="System.Text.Json" />
  </ItemGroup>

</Project>