<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../ServiceBusPoc.Core/ServiceBusPoc.Core.csproj" />
    <ProjectReference Include="../Shared/ServiceBusPoc.DigitalSite.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Adyen" Version="36.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Catalog/site-content.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
